@startuml
class Covariance <<StateType>>
class StandardBase <<StateType>>{ 
    #P:Covariance<StateType>
}
class SystemModel
class LinearizedSystemModel{
    action()
}
StandardBase *-- Covariance
StandardBase <|-down- SystemModel
SystemModel <|-down- LinearizedSystemModel

class KalmanFilterBase
class StandardFilterBase
StandardBase <|-down- StandardFilterBase
class ExtendedKalmanFilter
KalmanFilterBase <|-down- ExtendedKalmanFilter
StandardFilterBase <|-down- ExtendedKalmanFilter
@enduml